스프링 6주차 과제 PR
CodeSoom/spring-week6-assignment-1 pull request #42
Opened 2021-09-15 04:02 UTC by kiheo

이번주도 잘부탁드립니다.

2021-09-15 12:15 UTC, johngrib reviewed
화이팅!

2021-09-16 12:12 UTC, johngrib commented on app/src/main/java/com/codesoom/assignment/application/AuthenticationService.java
> +public class AuthenticationService {
이렇게 중요한 클래스의 public 메소드는 javadoc 주석을 작성하는 습관을 들입시다.

2021-09-16 12:12 UTC, johngrib commented on app/src/main/java/com/codesoom/assignment/application/AuthenticationService.java
> +                .claim("userId", 1L)
`1L`이 하드코딩되어 있는 것 같군요.

2021-09-16 12:12 UTC, johngrib commented on app/src/test/java/com/codesoom/assignment/controllers/SessionControllerTest.java
> +    private static final String VALID_TOKEN = "eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOjF9.neCsyNLzy3lQ4o2yliotWT06FwSGZagaHpKdAkjnGGw";
`VALID_TOKEN`을 이렇게 하드코딩해 두지 않고, 테스트 준비에서 토큰을 만들어서 `VALID_TOKEN`으로 할당해 보세요.

2021-09-18 13:30 UTC, kiheo commented on app/src/test/java/com/codesoom/assignment/controllers/SessionControllerTest.java
> +    private static final String VALID_TOKEN = "eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOjF9.neCsyNLzy3lQ4o2yliotWT06FwSGZagaHpKdAkjnGGw";
넵 setup을 통해 발행하도록 변경했습니다.

2021-09-18 13:38 UTC, kiheo commented on app/src/main/java/com/codesoom/assignment/application/AuthenticationService.java
> +public class AuthenticationService {
넵 javadoc작성해서 등록하겠습니다.

2021-09-18 13:38 UTC, kiheo commented on app/src/main/java/com/codesoom/assignment/application/AuthenticationService.java
> +                .claim("userId", 1L)
수정했습니다!

2021-09-19 05:05 UTC, kiheo commented
최근 강의를 집중해서 못들었습니다.. 자꾸 Autowired의 사용과 생성자로 주입되는 방식의 차이를 이해를 못해서 NPE에서 헤메고있습니다. 
beforeeach에서 user를 생성했으나 test에서는 못찾고 있습니다. 
좀 더 시간을 내서 지난 강의를 듣고 잘못사용된 부분을 찾아보겠습니다.

2021-09-19 12:30 UTC, johngrib commented on app/src/main/java/com/codesoom/assignment/application/AuthenticationService.java
> +    JwtUtil jwtUtil;
이렇게 하지 않아도 됩니다. `@Autowired`는 이제 권장되지 않는 방식이고, 사용이 점점 줄고 있습니다. 이 라인을 삭제하고 아래에 주석처리한 생성자의 주석을 풀어 주세요.

2021-09-19 12:39 UTC, johngrib commented
> 최근 강의를 집중해서 못들었습니다.. 자꾸 Autowired의 사용과 생성자로 주입되는 방식의 차이를 이해를 못해서 NPE에서 헤메고있습니다.
> beforeeach에서 user를 생성했으나 test에서는 못찾고 있습니다.
> 좀 더 시간을 내서 지난 강의를 듣고 잘못사용된 부분을 찾아보겠습니다.

`@RequestBody`를 빼먹으셨어요. 이거 추가하면 잘 돌아갈 겁니다. `@Autowired`는 지금 당면하신 문제랑 관계가 없어요.

![image](https://user-images.githubusercontent.com/1855714/133927799-092a4d2f-0b85-439b-adf0-c0652b6c1099.png)

2021-09-27 11:43 UTC, johngrib requested changes
PR의 머지 대상 브랜치가 `main`으로 되어 있습니다. `main`에 머지되지 않도록 수정해 주세요. `Edit` 버튼을 클릭한 다음 수정해 주시면 됩니다.

![image](https://user-images.githubusercontent.com/1855714/134901631-b51b2b06-38d3-4d24-906e-d666b692ad14.png)

2021-09-27 11:50 UTC, kiheo commented
PR 수정했습니다. 감사합니다!

2021-09-28 11:58 UTC, merged